services:
  next-app:
    ports:
      - "3005:3000"
    volumes:
      - "./src:/app/src"
    build: .
    # env_file:
      #$ this is already getting picked when I run the npm script 
      # - config/local.env 



  #ยก This is a test. NEED TO EXPLAIN WHY
  redis:
    image: busybox
    command: sh -c "echo 'redis placeholder'; sleep infinity"