services:
  next-app:
    networks: #! This is assuming you are running a Redis instance and setting that Redis instance to run in a custom network called paikynet.
      - default
      - paikynet
    command: "npm run dev_docker_network"
networks:
  default:
  paikynet:
    external: true