services:
  next-app:
    ports:
      - "3005:3000"
    volumes:
      - "./src:/app/src"
    build: .
    # env_file:
      #$ this is already getting picked when I run the npm script 
      # - config/local.env 
    
  redis:
    